"""Added profile info

Revision ID: 0fbb9665724c
Revises: f372f4fc9331
Create Date: 2022-08-05 13:41:44.276810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fbb9665724c'
down_revision = 'f372f4fc9331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('surname', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('phone_number', sa.String(length=15), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('fields_of_interest', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'fields_of_interest')
    op.drop_column('user', 'email')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'surname')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
