"""Added job_links column to SavedJob

Revision ID: f372f4fc9331
Revises: 02a52d813bb5
Create Date: 2022-08-02 16:13:45.760347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f372f4fc9331'
down_revision = '02a52d813bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_job', sa.Column('job_links', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_job', 'job_links')
    # ### end Alembic commands ###
